// Mock Prisma Client for TypeScript compilation
// In production, this would be generated by `npx prisma generate`

interface WhereClause {
  [key: string]: any;
}

class MockTable<T extends Record<string, any>> {
  private rows: T[] = [];

  constructor(private tableName: string) {}

  private matchesWhere(row: T, where?: WhereClause): boolean {
    if (!where) return true;
    return Object.entries(where).every(([key, value]) => row[key] === value);
  }

  async findFirst({ where }: { where?: WhereClause }) {
    return this.rows.find((row) => this.matchesWhere(row, where)) ?? null;
  }

  async findMany({ where, orderBy, take }: { where?: WhereClause; orderBy?: any; take?: number }) {
    let results = this.rows.filter((row) => this.matchesWhere(row, where));

    if (orderBy) {
      const [field, direction] = Object.entries(orderBy)[0] as [string, 'asc' | 'desc'];
      results = results.sort((a, b) => {
        if (a[field] === b[field]) return 0;
        const order = a[field] > b[field] ? 1 : -1;
        return direction === 'desc' ? -order : order;
      });
    }

    if (take) {
      results = results.slice(0, take);
    }

    return results;
  }

  async create({ data }: { data: T }) {
    this.rows.push(data);
    return data;
  }

  async update({ where, data }: { where: WhereClause; data: Partial<T> }) {
    const index = this.rows.findIndex((row) => this.matchesWhere(row, where));
    if (index === -1) {
      throw new Error(`Record not found in ${this.tableName}`);
    }
    this.rows[index] = { ...this.rows[index], ...data } as T;
    return this.rows[index];
  }

  async updateMany({ where, data }: { where: WhereClause; data: Partial<T> }) {
    let count = 0;
    this.rows = this.rows.map((row) => {
      if (this.matchesWhere(row, where)) {
        count += 1;
        return { ...row, ...data } as T;
      }
      return row;
    });
    return { count };
  }

  async delete({ where }: { where: WhereClause }) {
    const index = this.rows.findIndex((row) => this.matchesWhere(row, where));
    if (index === -1) {
      throw new Error(`Record not found in ${this.tableName}`);
    }
    const [deleted] = this.rows.splice(index, 1);
    return deleted;
  }
}

export class PrismaClient {
  tenants = new MockTable<any>('tenants');
  profiles = new MockTable<any>('profiles');
  customers = new MockTable<any>('customers');
  customer_policies = new MockTable<any>('customer_policies');
  documents = new MockTable<any>('documents');
  audit_logs = new MockTable<any>('audit_logs');
  notifications = new MockTable<any>('notifications');
  claims = new MockTable<any>('claims');
  commissions = new MockTable<any>('commissions');
  leads = new MockTable<any>('leads');
  renewals = new MockTable<any>('renewals');
  premium_payments = new MockTable<any>('premium_payments');
  family_members = new MockTable<any>('family_members');
  endorsements = new MockTable<any>('endorsements');
  message_templates = new MockTable<any>('message_templates');
  compliance_reports = new MockTable<any>('compliance_reports');
  knowledge_articles = new MockTable<any>('knowledge_articles');
  ai_insights = new MockTable<any>('ai_insights');
  security_events = new MockTable<any>('security_events');
  performance_metrics = new MockTable<any>('performance_metrics');

  $queryRaw: any = async () => [];
  $connect: any = async () => {};
  $disconnect: any = async () => {};
}

export const prisma = new PrismaClient();

// This file should be replaced with the actual generated Prisma client
// Run: npx prisma generate
